spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      static: #   数据源基本配置
          username: root
          url: jdbc:mysql://127.0.0.1:3306/static_dev?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=UTC
          password: root
    
      game: #   数据源基本配置
            username: root
            password: root
            url: jdbc:mysql://127.0.0.1:3306/game_server_dev?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=UTC
    
      
          #    数据源其他配置
      initialSize: 128
      maxActive: 128
      minIdle: 128
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
#     配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
 
---
spring:
   profiles: pro
   datasource:
 #   数据源基本配置
     username: root
     password: love@toor
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/sharinggirl?characterEncoding=utf8&useSSL=false
     type: com.alibaba.druid.pool.DruidDataSource
 #   数据源其他配置
     initialSize: 128
     minIdle: 128
     maxActive: 128
     maxWait: 60000
     timeBetweenEvictionRunsMillis: 60000
     minEvictableIdleTimeMillis: 300000
     validationQuery: SELECT 1 FROM DUAL
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
 #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
     #filters: stat,wall,log4j
     maxPoolPreparedStatementPerConnectionSize: 20
     useGlobalDataSourceStat: true
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
 